---
- hosts: localhost
  tasks:
    - name: add user
      user:
        name: ravi
        state: present
        
    - name: add group
      group:
        name: dev
        state: present
    
    - name: add package
      yum:
        name: httpd
        state: present
...